fix(deps): update dependency axios to ^1.7.7 (#2761)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [axios](https://axios-http.com)
([source](https://redirect.github.com/axios/axios)) | [`^1.7.2` ->
`^1.7.7`](https://renovatebot.com/diffs/npm/axios/1.7.4/1.7.7) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/axios/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/axios/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/axios/1.7.4/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/axios/1.7.4/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>axios/axios (axios)</summary>

###
[`v1.7.7`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#177-2024-08-31)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.6...v1.7.7)

##### Bug Fixes

- **fetch:** fix stream handling in Safari by fallback to using a stream
reader instead of an async iterator;
([#&#8203;6584](https://redirect.github.com/axios/axios/issues/6584))
([d198085](https://redirect.github.com/axios/axios/commit/d1980854fee1765cd02fa0787adf5d6e34dd9dcf))
- **http:** fixed support for IPv6 literal strings in url
([#&#8203;5731](https://redirect.github.com/axios/axios/issues/5731))
([364993f](https://redirect.github.com/axios/axios/commit/364993f0d8bc6e0e06f76b8a35d2d0a35cab054c))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/10539109?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/>
[Rishi556](https://redirect.github.com/Rishi556 "+39/-1 (#&#8203;5731
)")
- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+27/-7
(#&#8203;6584 )")

###
[`v1.7.6`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#176-2024-08-30)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.5...v1.7.6)

##### Bug Fixes

- **fetch:** fix content length calculation for FormData payload;
([#&#8203;6524](https://redirect.github.com/axios/axios/issues/6524))
([085f568](https://redirect.github.com/axios/axios/commit/085f56861a83e9ac02c140ad9d68dac540dfeeaa))
- **fetch:** optimize signals composing logic;
([#&#8203;6582](https://redirect.github.com/axios/axios/issues/6582))
([df9889b](https://redirect.github.com/axios/axios/commit/df9889b83c2cc37e9e6189675a73ab70c60f031f))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+98/-46
(#&#8203;6582 )")
- <img
src="https://avatars.githubusercontent.com/u/3534453?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Jacques
Germishuys](https://redirect.github.com/jacquesg "+5/-1 (#&#8203;6524
)")
- <img
src="https://avatars.githubusercontent.com/u/53894505?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/>
[kuroino721](https://redirect.github.com/kuroino721 "+3/-1 (#&#8203;6575
)")

###
[`v1.7.5`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#175-2024-08-23)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.4...v1.7.5)

##### Bug Fixes

- **adapter:** fix undefined reference to hasBrowserEnv
([#&#8203;6572](https://redirect.github.com/axios/axios/issues/6572))
([7004707](https://redirect.github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1))
- **core:** add the missed implementation of AxiosError#status property;
([#&#8203;6573](https://redirect.github.com/axios/axios/issues/6573))
([6700a8a](https://redirect.github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852))
- **core:** fix `ReferenceError: navigator is not defined` for custom
environments;
([#&#8203;6567](https://redirect.github.com/axios/axios/issues/6567))
([fed1a4b](https://redirect.github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794))
- **fetch:** fix credentials handling in Cloudflare workers
([#&#8203;6533](https://redirect.github.com/axios/axios/issues/6533))
([550d885](https://redirect.github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+187/-83
(#&#8203;6573 #&#8203;6567 #&#8203;6566 #&#8203;6564 #&#8203;6563
#&#8203;6557 #&#8203;6556 #&#8203;6555 #&#8203;6554 #&#8203;6552 )")
- <img
src="https://avatars.githubusercontent.com/u/2495809?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Antonin
Bas](https://redirect.github.com/antoninbas "+6/-6 (#&#8203;6572 )")
- <img
src="https://avatars.githubusercontent.com/u/5406212?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Hans Otto
Wirtz](https://redirect.github.com/hansottowirtz "+4/-1 (#&#8203;6533
)")

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/fwouts/previewjs).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOC4xMjAuMSIsInVwZGF0ZWRJblZlciI6IjM4LjEyMC4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>